review changes

diff --git a/.github/workflows/cpp-test-pr.yml b/.github/workflows/cpp-test-pr.yml
--- a/.github/workflows/cpp-test-pr.yml
+++ b/.github/workflows/cpp-test-pr.yml
@@ -110,9 +110,7 @@ jobs:
 
   dry-semantic-release:
     runs-on: ubuntu-latest
-    needs: [test-repository]
-    outputs:
-      new_release: ${{ steps.semantic.outputs.new_release_published }}
+    needs: prepare
     steps:
       - uses: actions/checkout@v4
       - name: Semantic Release
@@ -122,24 +120,15 @@ jobs:
           dry_run: true
         env:
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
-      - name: Send message on failure
+      - name: Failed for non semantic commit
         if: steps.semantic.outputs.new_release_published == 'false'
         run: | 
-            const message = 'PR is not mergeable: no semantic commit message found'
-                core.setFailed(message)
-        if: failure()
-        id: slack
-        uses: slackapi/slack-github-action@v1
-        with:
-          channel-id: C0598GTCLGH
-          slack-message: "${{ inputs.branch }}: PR not mergeable: no semantic commit message found\n${{ steps.check.outputs.result }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-        env:
-          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+            echo "::error PR is not mergeable: no semantic commit message found"
+            exit 1
 
   release:
     runs-on: ubuntu-latest
-    needs: [dry-semantic-release]
-    if: needs.dry-semantic-release.outputs.new_release == 'true'
+    needs: [test-repository, dry-semantic-release]
     steps:
       - name: Create Release
         uses: actions/github-script@v7
