again

diff --git a/.github/workflows/py-test-pr.yml b/.github/workflows/py-test-pr.yml
--- a/.github/workflows/py-test-pr.yml
+++ b/.github/workflows/py-test-pr.yml
@@ -51,22 +51,14 @@ jobs:
           python -m pip install --upgrade pip
           pip install mypy
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          mypy . --show-column-numbers --show-error-codes --strict || true
       - name: Setup reviewdog
         uses: reviewdog/action-setup@v1
       - name: Run mypy and reviewdog
         env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          mypy . --show-column-numbers --show-error-codes --strict | \
-          reviewdog -efm="%E%f:%l:%c: error: %m" \
-                    -efm="%E%f:%l: error: %m" \
-                    -efm="%W%f:%l:%c: warning: %m" \
-                    -efm="%W%f:%l: warning: %m" \
-                    -name="mypy" \
-                    -reporter=github-pr-review \
-                    -level=warning \
-                    -filter-mode=added \
-                    -fail-level=any
+          mypy . --show-column-numbers --show-error-codes --strict | reviewdog -efm="%E%f:%l:%c: error: %m" -efm="%E%f:%l: error: %m" -efm="%W%f:%l:%c: warning: %m" -efm="%W%f:%l: warning: %m" -name="mypy" -reporter=github-pr-review -level=warning -filter-mode=added -fail-level=any
 
   test-repository:
     needs: prepare
